### ISSUE TITLE
Is it possible to use Cardio to call stored WorkoutSession data?

### ISSUE THREAD

**Issue by jernej99** [kitasuke/Cardio#20]
First of all thank you for great extension, I have implemented it in my app and works like charm.
There is one more thing I wish to do, and can not make it work. 
When cardio.save()... is called I want to access this stored data about workout session, such as average, low, max of pulse, distance etc. to display it to user and save it to iOS app under workout statistics.

Is that operation possible using Cardio extension or do I have to use standard HealthKit Library?

**Comment by kitasuke** [comment]
Thanks for using it!
Please give me some time, I'll think about a better way.

**Comment by kitasuke** [comment]
Sorry for late reply.
I've just released a new version. It passes HKWorkout object which is actually saved in HealthKit as an argument of handler for save method.
Please take a look!
