### ISSUE TITLE
watchOS 3?

### ISSUE THREAD

**Issue by basememara** [kitasuke/Cardio#26]
Great wrapper, very clean API! Any plans to update to watchOS 3?

**Comment by kitasuke** [comment]
Thanks! I'll support it soon.

**Comment by seanrice** [comment]
Awesome!!! marvelous API.

**Comment by kitasuke** [comment]
Version `0.1.0` was just released! I'll support Swift 3.0 later.

**Comment by seanrice** [comment]
note: i had to modify Cartfile to include new version number...  
github "kitasuke/Cardio" ~> 0.1.0

**Comment by kitasuke** [comment]
Did you run `carthage update` ?
