### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported with Swift 3

### ISSUE THREAD

**Issue by seanrice** [kitasuke/Cardio#28]
SOS =) installed 0.1.0 - delete/replaced Cardio.xcodeproj in my test app, updated cartfile for 0.1.0, ran carthage update (which includes Result 2.1.3 framework), command-shift-k, command-option-shift-k, even deleted DerivedMedia folder manually ... but ... getting compiler error. 

ERROR: "Module compiled with Swift 2.3 cannot be imported with Swift 3.0.1"

I'm running latest Mac OS 10.12.1 and Xcode 8 on iMac. 
See screenshot.

![screen shot 2016-11-24 at 11 02 29 pm](https://cloud.githubusercontent.com/assets/1357349/20614521/54ee438c-b29d-11e6-8ffc-f2579fc33726.png)

**Comment by kitasuke** [comment]
Swift 3+ is not supported yet, will do soon.

**Comment by seanrice** [comment]
forgive me =) should have realized. thanks!!!

**Comment by kitasuke** [comment]
The latest version(1.0.0) has just released including Swift 3 support. Please use this version.
